version: '3'

services:
  db:
    container_name: 'sahachart-postgres'
    image: 'postgres:latest'
    ports:
      - 54322:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
    restart: 'unless-stopped'